import type { Metadata } from "next";
import { Tomorrow } from "next/font/google";
import "./globals.css";

const tomorrow = Tomorrow({
    subsets: ['latin'],
    weight: ['400', '700']
});

export const metadata: Metadata = {
  title: "Morse Code",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${tomorrow.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
